services:

  service:
    container_name: notification_api
    build:
      context: api/src/app
      dockerfile: ./Dockerfile
    entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 8010
    ports:
      - 8010
    env_file:
      - api/src/app/.env

  nginx:
    container_name: notification_nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - nginx:/var/log/nginx/
    depends_on:
      - service

  db:
    image: postgres:13-alpine
    container_name: notification_db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  rabbitmq:
      image: rabbitmq:3-management
      container_name: 'notification_rabbitmq'
      volumes:
        - rabbit_data:/var/lib/rabbitmq/
      ports:
        - 5672:5672
        - 15672:15672

volumes:
  nginx:
  db_data:
  rabbit_data: