services:

  service:
    container_name: notification_api
    build:
      context: api/src/app
      dockerfile: ./Dockerfile
    entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 8010
    ports:
      - 8010
    env_file:
      - api/src/app/.env

  nginx:
    container_name: notification_nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - nginx:/var/log/nginx/
    depends_on:
      - service



volumes:
  nginx: