name: Linter check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy lxml wemake-python-styleguide flake8-html
      - name: make-linter-report-directory
        run: |
          mkdir -p lint_report/api/src/app/styleguide/
          mkdir -p lint_report/worker/src/styleguide/
          mkdir -p lint_report/admin/app/notification/styleguide/
          mkdir -p lint_report/api/src/app/mypy/
          mkdir -p lint_report/worker/src/mypy/
          mkdir -p lint_report/admin/app/notification/mypy/
      - name: mypy
        run: |
          mypy --html-report lint_report/api/src/app/mypy/ api/src/app* || true
          mypy --html-report lint_report/worker/src/mypy/ worker/src* || true
          mypy --html-report lint_report/admin/app/notification/mypy/ admin/app/notification* || true
      - name: lint-codestyle
        run: |
          flake8 ugc/src/api --exit-zero --format=html --htmldir=lint_report/api/src/app/styleguide/
          flake8 ugc/src/etl --exit-zero --format=html --htmldir=lint_report/worker/src/styleguide/
          flake8 user_data_api/src/app --exit-zero --format=html --htmldir=lint_report/admin/app/notification/styleguide/
      - name: load-report
        uses: actions/upload-artifact@v3.1.0
        with:
          name: lint_report
          path: lint_report/